//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resAvaloniaOps {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resAvaloniaOps() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resAvaloniaOps", typeof(resAvaloniaOps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string dlgFolderUserAssets {
            get {
                return ResourceManager.GetString("dlgFolderUserAssets", resourceCulture);
            }
        }
        
        public static string dlgFolderROMParent {
            get {
                return ResourceManager.GetString("dlgFolderROMParent", resourceCulture);
            }
        }
        
        public static string dlgFolderIcoOutput {
            get {
                return ResourceManager.GetString("dlgFolderIcoOutput", resourceCulture);
            }
        }
        
        public static string dlgFolderLinkCopy {
            get {
                return ResourceManager.GetString("dlgFolderLinkCopy", resourceCulture);
            }
        }
        
        public static string dlgFolderFallback {
            get {
                return ResourceManager.GetString("dlgFolderFallback", resourceCulture);
            }
        }
        
        public static string pckFileTypeExe {
            get {
                return ResourceManager.GetString("pckFileTypeExe", resourceCulture);
            }
        }
        
        public static string pckFileTypeAppI {
            get {
                return ResourceManager.GetString("pckFileTypeAppI", resourceCulture);
            }
        }
        
        public static string pckFileTypeSh {
            get {
                return ResourceManager.GetString("pckFileTypeSh", resourceCulture);
            }
        }
        
        public static string pckFileTypeConf {
            get {
                return ResourceManager.GetString("pckFileTypeConf", resourceCulture);
            }
        }
        
        public static string pckFileTypeIco {
            get {
                return ResourceManager.GetString("pckFileTypeIco", resourceCulture);
            }
        }
        
        public static string pckFileTypeConvI {
            get {
                return ResourceManager.GetString("pckFileTypeConvI", resourceCulture);
            }
        }
        
        public static string pckFileTypeIcon {
            get {
                return ResourceManager.GetString("pckFileTypeIcon", resourceCulture);
            }
        }
        
        public static string pckFileTypeWinLnk {
            get {
                return ResourceManager.GetString("pckFileTypeWinLnk", resourceCulture);
            }
        }
        
        public static string pckFileTypeLinLnk {
            get {
                return ResourceManager.GetString("pckFileTypeLinLnk", resourceCulture);
            }
        }
        
        public static string dlgFileLINKDir {
            get {
                return ResourceManager.GetString("dlgFileLINKDir", resourceCulture);
            }
        }
        
        public static string dlgFileOutFallback {
            get {
                return ResourceManager.GetString("dlgFileOutFallback", resourceCulture);
            }
        }
        
        public static string dlgFileRAexe {
            get {
                return ResourceManager.GetString("dlgFileRAexe", resourceCulture);
            }
        }
        
        public static string dlgFileRAroms {
            get {
                return ResourceManager.GetString("dlgFileRAroms", resourceCulture);
            }
        }
        
        public static string dlgFileRAcfg {
            get {
                return ResourceManager.GetString("dlgFileRAcfg", resourceCulture);
            }
        }
        
        public static string dlgFileIcon {
            get {
                return ResourceManager.GetString("dlgFileIcon", resourceCulture);
            }
        }
        
        public static string dlgFileInFallback {
            get {
                return ResourceManager.GetString("dlgFileInFallback", resourceCulture);
            }
        }
    }
}
