//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resAboutWindow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resAboutWindow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resAboutWindow", typeof(resAboutWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string wndTitle {
            get {
                return ResourceManager.GetString("wndTitle", resourceCulture);
            }
        }
        
        public static string lblDesc {
            get {
                return ResourceManager.GetString("lblDesc", resourceCulture);
            }
        }
        
        public static string lblCopyright {
            get {
                return ResourceManager.GetString("lblCopyright", resourceCulture);
            }
        }
        
        public static string lblMaintainer {
            get {
                return ResourceManager.GetString("lblMaintainer", resourceCulture);
            }
        }
        
        public static string lblContributors {
            get {
                return ResourceManager.GetString("lblContributors", resourceCulture);
            }
        }
        
        public static string lblAttributions {
            get {
                return ResourceManager.GetString("lblAttributions", resourceCulture);
            }
        }
        
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
    }
}
