//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resGeneric {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resGeneric() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resGeneric", typeof(resGeneric).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        public static string btnExecute {
            get {
                return ResourceManager.GetString("btnExecute", resourceCulture);
            }
        }
        
        public static string btnRetry {
            get {
                return ResourceManager.GetString("btnRetry", resourceCulture);
            }
        }
        
        public static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        public static string btnDiscard {
            get {
                return ResourceManager.GetString("btnDiscard", resourceCulture);
            }
        }
        
        public static string btnDefault {
            get {
                return ResourceManager.GetString("btnDefault", resourceCulture);
            }
        }
        
        public static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        public static string btnCustom {
            get {
                return ResourceManager.GetString("btnCustom", resourceCulture);
            }
        }
    }
}
