//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resMainView {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resMainView() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resMainView", typeof(resMainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblTITLE {
            get {
                return ResourceManager.GetString("lblTITLE", resourceCulture);
            }
        }
        
        public static string lblRADir {
            get {
                return ResourceManager.GetString("lblRADir", resourceCulture);
            }
        }
        
        public static string lblROMDir {
            get {
                return ResourceManager.GetString("lblROMDir", resourceCulture);
            }
        }
        
        public static string chkContentless {
            get {
                return ResourceManager.GetString("chkContentless", resourceCulture);
            }
        }
        
        public static string lblCore {
            get {
                return ResourceManager.GetString("lblCore", resourceCulture);
            }
        }
        
        public static string tipSubSys {
            get {
                return ResourceManager.GetString("tipSubSys", resourceCulture);
            }
        }
        
        public static string lblNoCores {
            get {
                return ResourceManager.GetString("lblNoCores", resourceCulture);
            }
        }
        
        public static string lblConfig {
            get {
                return ResourceManager.GetString("lblConfig", resourceCulture);
            }
        }
        
        public static string chkFull {
            get {
                return ResourceManager.GetString("chkFull", resourceCulture);
            }
        }
        
        public static string chkVerb {
            get {
                return ResourceManager.GetString("chkVerb", resourceCulture);
            }
        }
        
        public static string chkAccessi {
            get {
                return ResourceManager.GetString("chkAccessi", resourceCulture);
            }
        }
        
        public static string lblLinkDir {
            get {
                return ResourceManager.GetString("lblLinkDir", resourceCulture);
            }
        }
        
        public static string lblLinkName {
            get {
                return ResourceManager.GetString("lblLinkName", resourceCulture);
            }
        }
        
        public static string lblLinkDeskDir {
            get {
                return ResourceManager.GetString("lblLinkDeskDir", resourceCulture);
            }
        }
        
        public static string lblDesc {
            get {
                return ResourceManager.GetString("lblDesc", resourceCulture);
            }
        }
        
        public static string txtDesc_mark {
            get {
                return ResourceManager.GetString("txtDesc_mark", resourceCulture);
            }
        }
        
        public static string txtDesc_tip {
            get {
                return ResourceManager.GetString("txtDesc_tip", resourceCulture);
            }
        }
        
        public static string lblICON {
            get {
                return ResourceManager.GetString("lblICON", resourceCulture);
            }
        }
        
        public static string rdoIconDef {
            get {
                return ResourceManager.GetString("rdoIconDef", resourceCulture);
            }
        }
        
        public static string rdoIconCus {
            get {
                return ResourceManager.GetString("rdoIconCus", resourceCulture);
            }
        }
        
        public static string lblIconNoImage {
            get {
                return ResourceManager.GetString("lblIconNoImage", resourceCulture);
            }
        }
        
        public static string tipBrowse {
            get {
                return ResourceManager.GetString("tipBrowse", resourceCulture);
            }
        }
        
        public static string tipPatches {
            get {
                return ResourceManager.GetString("tipPatches", resourceCulture);
            }
        }
        
        public static string tipAppendConfig {
            get {
                return ResourceManager.GetString("tipAppendConfig", resourceCulture);
            }
        }
        
        public static string genFatalError {
            get {
                return ResourceManager.GetString("genFatalError", resourceCulture);
            }
        }
        
        public static string tipIconNoImage {
            get {
                return ResourceManager.GetString("tipIconNoImage", resourceCulture);
            }
        }
        
        public static string dllErrorHead {
            get {
                return ResourceManager.GetString("dllErrorHead", resourceCulture);
            }
        }
        
        public static string dllErrorMess {
            get {
                return ResourceManager.GetString("dllErrorMess", resourceCulture);
            }
        }
        
        public static string comboDefItem {
            get {
                return ResourceManager.GetString("comboDefItem", resourceCulture);
            }
        }
        
        public static string LinPopUp_Title {
            get {
                return ResourceManager.GetString("LinPopUp_Title", resourceCulture);
            }
        }
        
        public static string LinPopUp_Head {
            get {
                return ResourceManager.GetString("LinPopUp_Head", resourceCulture);
            }
        }
        
        public static string LinPopUp_Mess {
            get {
                return ResourceManager.GetString("LinPopUp_Mess", resourceCulture);
            }
        }
        
        public static string popMissReq_Mess {
            get {
                return ResourceManager.GetString("popMissReq_Mess", resourceCulture);
            }
        }
        
        public static string popMissReq_Title {
            get {
                return ResourceManager.GetString("popMissReq_Title", resourceCulture);
            }
        }
        
        public static string popSingleOutput1_Mess {
            get {
                return ResourceManager.GetString("popSingleOutput1_Mess", resourceCulture);
            }
        }
        
        public static string genSucces {
            get {
                return ResourceManager.GetString("genSucces", resourceCulture);
            }
        }
        
        public static string popSingleOutput0_Mess {
            get {
                return ResourceManager.GetString("popSingleOutput0_Mess", resourceCulture);
            }
        }
        
        public static string popSingleOutput0_Head {
            get {
                return ResourceManager.GetString("popSingleOutput0_Head", resourceCulture);
            }
        }
        
        public static string genError {
            get {
                return ResourceManager.GetString("genError", resourceCulture);
            }
        }
        
        public static string popMultiOutput1_Mess {
            get {
                return ResourceManager.GetString("popMultiOutput1_Mess", resourceCulture);
            }
        }
        
        public static string popMultiOutput0_Head {
            get {
                return ResourceManager.GetString("popMultiOutput0_Head", resourceCulture);
            }
        }
        
        public static string genWarning {
            get {
                return ResourceManager.GetString("genWarning", resourceCulture);
            }
        }
        
        public static string popLinkSucces {
            get {
                return ResourceManager.GetString("popLinkSucces", resourceCulture);
            }
        }
        
        public static string popLinkFailure {
            get {
                return ResourceManager.GetString("popLinkFailure", resourceCulture);
            }
        }
        
        public static string LinPopUp_Mess2 {
            get {
                return ResourceManager.GetString("LinPopUp_Mess2", resourceCulture);
            }
        }
        
        public static string btnMoreParams {
            get {
                return ResourceManager.GetString("btnMoreParams", resourceCulture);
            }
        }
        
        public static string dllErrorMess2 {
            get {
                return ResourceManager.GetString("dllErrorMess2", resourceCulture);
            }
        }
        
        public static string popIconsError_Tittle {
            get {
                return ResourceManager.GetString("popIconsError_Tittle", resourceCulture);
            }
        }
        
        public static string popIconsError_Mess {
            get {
                return ResourceManager.GetString("popIconsError_Mess", resourceCulture);
            }
        }
        
        public static string popIconsError_Mess2 {
            get {
                return ResourceManager.GetString("popIconsError_Mess2", resourceCulture);
            }
        }
    }
}
