//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resMainExtras {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resMainExtras() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resMainExtras", typeof(resMainExtras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string tittleEntryName {
            get {
                return ResourceManager.GetString("tittleEntryName", resourceCulture);
            }
        }
        
        public static string lblFriendlyName {
            get {
                return ResourceManager.GetString("lblFriendlyName", resourceCulture);
            }
        }
        
        public static string lblFileName {
            get {
                return ResourceManager.GetString("lblFileName", resourceCulture);
            }
        }
        
        public static string txtFriendlyName_Tip {
            get {
                return ResourceManager.GetString("txtFriendlyName_Tip", resourceCulture);
            }
        }
        
        public static string txtFileName_Tip {
            get {
                return ResourceManager.GetString("txtFileName_Tip", resourceCulture);
            }
        }
        
        public static string lblExt_Tip {
            get {
                return ResourceManager.GetString("lblExt_Tip", resourceCulture);
            }
        }
        
        public static string chkCustomFilename {
            get {
                return ResourceManager.GetString("chkCustomFilename", resourceCulture);
            }
        }
        
        public static string btnClear_Tip {
            get {
                return ResourceManager.GetString("btnClear_Tip", resourceCulture);
            }
        }
        
        public static string tittleSoftPatching {
            get {
                return ResourceManager.GetString("tittleSoftPatching", resourceCulture);
            }
        }
        
        public static string rdoNoPatch {
            get {
                return ResourceManager.GetString("rdoNoPatch", resourceCulture);
            }
        }
        
        public static string rdoUPSPatch {
            get {
                return ResourceManager.GetString("rdoUPSPatch", resourceCulture);
            }
        }
        
        public static string rdoBPSPatch {
            get {
                return ResourceManager.GetString("rdoBPSPatch", resourceCulture);
            }
        }
        
        public static string rdoIPSPatch {
            get {
                return ResourceManager.GetString("rdoIPSPatch", resourceCulture);
            }
        }
        
        public static string rdoXDPatch {
            get {
                return ResourceManager.GetString("rdoXDPatch", resourceCulture);
            }
        }
        
        public static string chkNoPatch_Tip2 {
            get {
                return ResourceManager.GetString("chkNoPatch_Tip2", resourceCulture);
            }
        }
        
        public static string chkNoPatch {
            get {
                return ResourceManager.GetString("chkNoPatch", resourceCulture);
            }
        }
        
        public static string chkNoPatch_Tip1 {
            get {
                return ResourceManager.GetString("chkNoPatch_Tip1", resourceCulture);
            }
        }
        
        public static string popNonSelected_Tittle {
            get {
                return ResourceManager.GetString("popNonSelected_Tittle", resourceCulture);
            }
        }
        
        public static string popNonSelected_Msg {
            get {
                return ResourceManager.GetString("popNonSelected_Msg", resourceCulture);
            }
        }
        
        public static string tittleAppendConfig {
            get {
                return ResourceManager.GetString("tittleAppendConfig", resourceCulture);
            }
        }
    }
}
