//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resMainView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resMainView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroLinker.Translations.resMainView", typeof(resMainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string btnExecute {
            get {
                return ResourceManager.GetString("btnExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string btnRetry {
            get {
                return ResourceManager.GetString("btnRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string chkAccessi {
            get {
                return ResourceManager.GetString("chkAccessi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contentless.
        /// </summary>
        public static string chkContentless {
            get {
                return ResourceManager.GetString("chkContentless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string chkFull {
            get {
                return ResourceManager.GetString("chkFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string chkVerb {
            get {
                return ResourceManager.GetString("chkVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string comboDefItem {
            get {
                return ResourceManager.GetString("comboDefItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of {0} has failed!.
        /// </summary>
        public static string dllErrorHead {
            get {
                return ResourceManager.GetString("dllErrorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import has failed with the following error:\n{0}\n\nWithout this library the program cannot accomplish its function..
        /// </summary>
        public static string dllErrorMess {
            get {
                return ResourceManager.GetString("dllErrorMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string genError {
            get {
                return ResourceManager.GetString("genError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        public static string genFatalError {
            get {
                return ResourceManager.GetString("genFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes.
        /// </summary>
        public static string genSucces {
            get {
                return ResourceManager.GetString("genSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string genWarning {
            get {
                return ResourceManager.GetString("genWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string lblConfig {
            get {
                return ResourceManager.GetString("lblConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core*.
        /// </summary>
        public static string lblCore {
            get {
                return ResourceManager.GetString("lblCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut description.
        /// </summary>
        public static string lblDesc {
            get {
                return ResourceManager.GetString("lblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon selection.
        /// </summary>
        public static string lblICON {
            get {
                return ResourceManager.GetString("lblICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item cannot be displayed.
        /// </summary>
        public static string lblIconNoImage {
            get {
                return ResourceManager.GetString("lblIconNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop directory.
        /// </summary>
        public static string lblLinkDeskDir {
            get {
                return ResourceManager.GetString("lblLinkDeskDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut output directory*.
        /// </summary>
        public static string lblLinkDir {
            get {
                return ResourceManager.GetString("lblLinkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Shortcut name*.
        /// </summary>
        public static string lblLinkName {
            get {
                return ResourceManager.GetString("lblLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;cores.txt&apos; not found!.
        /// </summary>
        public static string lblNoCores {
            get {
                return ResourceManager.GetString("lblNoCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetroArch executable*.
        /// </summary>
        public static string lblRADir {
            get {
                return ResourceManager.GetString("lblRADir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM directory*.
        /// </summary>
        public static string lblROMDir {
            get {
                return ResourceManager.GetString("lblROMDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetroLinker.
        /// </summary>
        public static string lblTITLE {
            get {
                return ResourceManager.GetString("lblTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name used here will be used as the visible name of the link, and as the name of the file itself..
        /// </summary>
        public static string LinPopUp_Head {
            get {
                return ResourceManager.GetString("LinPopUp_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, blank spaces will be replaced by &apos;-&apos; in the file name, for standard and convenience reasons.\n\n\nPress Cancel to no longer display this message..
        /// </summary>
        public static string LinPopUp_Mess {
            get {
                return ResourceManager.GetString("LinPopUp_Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string LinPopUp_Title {
            get {
                return ResourceManager.GetString("LinPopUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiered fields are missing.
        /// </summary>
        public static string popMissReq_Mess {
            get {
                return ResourceManager.GetString("popMissReq_Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Fields.
        /// </summary>
        public static string popMissReq_Title {
            get {
                return ResourceManager.GetString("popMissReq_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error while creating some links:.
        /// </summary>
        public static string popMultiOutput0_Head {
            get {
                return ResourceManager.GetString("popMultiOutput0_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All links were created succesfully.
        /// </summary>
        public static string popMultiOutput1_Mess {
            get {
                return ResourceManager.GetString("popMultiOutput1_Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred while creating the link.
        /// </summary>
        public static string popSingleOutput0_Head {
            get {
                return ResourceManager.GetString("popSingleOutput0_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation falied with the following error:\n{0}.
        /// </summary>
        public static string popSingleOutput0_Mess {
            get {
                return ResourceManager.GetString("popSingleOutput0_Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link file has been created succesfully.
        /// </summary>
        public static string popSingleOutput1_Mess {
            get {
                return ResourceManager.GetString("popSingleOutput1_Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string rdoIconCus {
            get {
                return ResourceManager.GetString("rdoIconCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string rdoIconDef {
            get {
                return ResourceManager.GetString("rdoIconDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Config.
        /// </summary>
        public static string tipAppendConfig {
            get {
                return ResourceManager.GetString("tipAppendConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string tipBrowse {
            get {
                return ResourceManager.GetString("tipBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can not display the selected icon. However, the selectited file will be used to create the shortcut..
        /// </summary>
        public static string tipIconNoImage {
            get {
                return ResourceManager.GetString("tipIconNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string tipPatches {
            get {
                return ResourceManager.GetString("tipPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsystem.
        /// </summary>
        public static string tipSubSys {
            get {
                return ResourceManager.GetString("tipSubSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Super Mario Bros. on RetroArch.
        /// </summary>
        public static string txtDesc_mark {
            get {
                return ResourceManager.GetString("txtDesc_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a description to the new shortcut.
        /// </summary>
        public static string txtDesc_tip {
            get {
                return ResourceManager.GetString("txtDesc_tip", resourceCulture);
            }
        }
    }
}
