//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroLinker.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resSettingsWindow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSettingsWindow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetroLinker.Translations.resSettingsWindow", typeof(resSettingsWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string tabGeneral {
            get {
                return ResourceManager.GetString("tabGeneral", resourceCulture);
            }
        }
        
        public static string tabPaths {
            get {
                return ResourceManager.GetString("tabPaths", resourceCulture);
            }
        }
        
        public static string tabOutput {
            get {
                return ResourceManager.GetString("tabOutput", resourceCulture);
            }
        }
        
        public static string popDefaults_Title {
            get {
                return ResourceManager.GetString("popDefaults_Title", resourceCulture);
            }
        }
        
        public static string popDefaults_Mess {
            get {
                return ResourceManager.GetString("popDefaults_Mess", resourceCulture);
            }
        }
        
        public static string lblCat_Appearance {
            get {
                return ResourceManager.GetString("lblCat_Appearance", resourceCulture);
            }
        }
        
        public static string swtThemeSwitch {
            get {
                return ResourceManager.GetString("swtThemeSwitch", resourceCulture);
            }
        }
        
        public static string chkThemeDefault {
            get {
                return ResourceManager.GetString("chkThemeDefault", resourceCulture);
            }
        }
        
        public static string swtThemeSwitch_On {
            get {
                return ResourceManager.GetString("swtThemeSwitch_On", resourceCulture);
            }
        }
        
        public static string swtThemeSwitch_Off {
            get {
                return ResourceManager.GetString("swtThemeSwitch_Off", resourceCulture);
            }
        }
        
        public static string lblCat_OtherGeneral {
            get {
                return ResourceManager.GetString("lblCat_OtherGeneral", resourceCulture);
            }
        }
        
        public static string chkPrevCONFIG {
            get {
                return ResourceManager.GetString("chkPrevCONFIG", resourceCulture);
            }
        }
        
        public static string lblCat_IconsGeneral {
            get {
                return ResourceManager.GetString("lblCat_IconsGeneral", resourceCulture);
            }
        }
        
        public static string chkCpyUserIcon {
            get {
                return ResourceManager.GetString("chkCpyUserIcon", resourceCulture);
            }
        }
        
        public static string tipCpyUserIcon {
            get {
                return ResourceManager.GetString("tipCpyUserIcon", resourceCulture);
            }
        }
        
        public static string lblCat_AserAssets {
            get {
                return ResourceManager.GetString("lblCat_AserAssets", resourceCulture);
            }
        }
        
        public static string lblCat_DefRADir {
            get {
                return ResourceManager.GetString("lblCat_DefRADir", resourceCulture);
            }
        }
        
        public static string lblCat_DefROMPath {
            get {
                return ResourceManager.GetString("lblCat_DefROMPath", resourceCulture);
            }
        }
        
        public static string blcUserAssets {
            get {
                return ResourceManager.GetString("blcUserAssets", resourceCulture);
            }
        }
        
        public static string lblCat_DEFLinkOutput {
            get {
                return ResourceManager.GetString("lblCat_DEFLinkOutput", resourceCulture);
            }
        }
        
        public static string chkAlwaysAskOutput {
            get {
                return ResourceManager.GetString("chkAlwaysAskOutput", resourceCulture);
            }
        }
        
        public static string lblDEFLinkOutput {
            get {
                return ResourceManager.GetString("lblDEFLinkOutput", resourceCulture);
            }
        }
        
        public static string chkMakeLinkCopy {
            get {
                return ResourceManager.GetString("chkMakeLinkCopy", resourceCulture);
            }
        }
        
        public static string lblCat_MakeLinkCopy {
            get {
                return ResourceManager.GetString("lblCat_MakeLinkCopy", resourceCulture);
            }
        }
        
        public static string lblCat_IcoOutput {
            get {
                return ResourceManager.GetString("lblCat_IcoOutput", resourceCulture);
            }
        }
        
        public static string chkExtractIco {
            get {
                return ResourceManager.GetString("chkExtractIco", resourceCulture);
            }
        }
        
        public static string tipExtractIco {
            get {
                return ResourceManager.GetString("tipExtractIco", resourceCulture);
            }
        }
        
        public static string chkIcoLinkName {
            get {
                return ResourceManager.GetString("chkIcoLinkName", resourceCulture);
            }
        }
        
        public static string tipUseDefaultIcoSavPath {
            get {
                return ResourceManager.GetString("tipUseDefaultIcoSavPath", resourceCulture);
            }
        }
        
        public static string blcIcoOutout {
            get {
                return ResourceManager.GetString("blcIcoOutout", resourceCulture);
            }
        }
        
        public static string blcIcoSavPath {
            get {
                return ResourceManager.GetString("blcIcoSavPath", resourceCulture);
            }
        }
        
        public static string strAddCustomCopyPath {
            get {
                return ResourceManager.GetString("strAddCustomCopyPath", resourceCulture);
            }
        }
        
        public static string strDefIcoSavPathItem0 {
            get {
                return ResourceManager.GetString("strDefIcoSavPathItem0", resourceCulture);
            }
        }
        
        public static string strDefIcoSavPathItem1 {
            get {
                return ResourceManager.GetString("strDefIcoSavPathItem1", resourceCulture);
            }
        }
        
        public static string strDefIcoSavPathItem2 {
            get {
                return ResourceManager.GetString("strDefIcoSavPathItem2", resourceCulture);
            }
        }
        
        public static string txtIcoSavPath1 {
            get {
                return ResourceManager.GetString("txtIcoSavPath1", resourceCulture);
            }
        }
        
        public static string txtIcoSavPath2 {
            get {
                return ResourceManager.GetString("txtIcoSavPath2", resourceCulture);
            }
        }
        
        public static string lblLocale {
            get {
                return ResourceManager.GetString("lblLocale", resourceCulture);
            }
        }
    }
}
